version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build_and_test:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - run:
          name: Collect coverage
          command: |
            . venv/bin/activate
            pip install coverage codecov
            coverage run --source=. manage.py test
            coverage xml
            codecov
workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test